Repository Open-Source-Chandigarh/Euphoria-Check, pull requests merged in 2024-05, with the labels that each got.

#63 updated the result page
  Public/styles/result.css
  app.js
  views/result.ejs
Labels: Gssoc

#95 Resolved issue #48: Added a custom error page
  .DS_Store
  .gitignore
  app.js
  utils/ExpressError.js
  views/customError.ejs
Labels: gssoc, level1

#116 Updated the top arrow in questions page
  Public/styles/question.css
  views/index.ejs
  views/questions.ejs
Labels: gssoc
